2025-01-22 10:32:50,138 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.8:5000
2025-01-22 10:32:50,139 [INFO] [33mPress CTRL+C to quit[0m
2025-01-22 10:32:50,142 [INFO]  * Restarting with stat
2025-01-22 10:32:52,770 [WARNING]  * Debugger is active!
2025-01-22 10:32:52,780 [INFO]  * Debugger PIN: 646-228-176
2025-01-22 11:30:10,440 [INFO]  * Detected change in 'C:\\Users\\leonardo\\Desktop\\Integração C6 Bank\\app.py', reloading
2025-01-22 11:30:12,846 [INFO]  * Restarting with stat
2025-01-22 11:30:16,549 [WARNING]  * Debugger is active!
2025-01-22 11:30:16,560 [INFO]  * Debugger PIN: 646-228-176
2025-01-22 11:32:11,382 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.8.0.4:5000
2025-01-22 11:32:11,383 [INFO] [33mPress CTRL+C to quit[0m
2025-01-22 11:32:11,386 [INFO]  * Restarting with stat
2025-01-22 11:32:13,762 [WARNING]  * Debugger is active!
2025-01-22 11:32:13,772 [INFO]  * Debugger PIN: 646-228-176
2025-01-22 11:32:27,530 [INFO] Recebido JSON do Zoho: {'external_reference_id': '0000107047', 'invoice_id': '5950246000000107047', 'amount': '10.0', 'due_date': '2025-01-20', 'instructions': '', 'payer': {'name': 'Leonardo', 'tax_id': '03845768002', 'email': 'leonardogotz@gmail.com', 'address': {'street': 'José Pereira Liberato', 'number': '3350', 'complement': '', 'city': 'Itajai', 'state': 'SC', 'zip_code': '88303401'}}}
2025-01-22 11:32:27,613 [ERROR] Erro na autenticação do C6: HTTPSConnectionPool(host='api.c6bank.com.br', port=443): Max retries exceeded with url: /oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018D7A022420>: Failed to resolve 'api.c6bank.com.br' ([Errno 11001] getaddrinfo failed)"))
2025-01-22 11:32:27,614 [ERROR] Erro na requisição ao C6: HTTPSConnectionPool(host='api.c6bank.com.br', port=443): Max retries exceeded with url: /oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018D7A022420>: Failed to resolve 'api.c6bank.com.br' ([Errno 11001] getaddrinfo failed)"))
2025-01-22 11:32:27,615 [ERROR] Erro no processamento: HTTPSConnectionPool(host='api.c6bank.com.br', port=443): Max retries exceeded with url: /oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018D7A022420>: Failed to resolve 'api.c6bank.com.br' ([Errno 11001] getaddrinfo failed)"))
2025-01-22 11:32:27,617 [INFO] 127.0.0.1 - - [22/Jan/2025 11:32:27] "[35m[1mPOST /zoho-webhook HTTP/1.1[0m" 500 -
2025-01-22 11:38:11,031 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.8.0.4:5000
2025-01-22 11:38:11,032 [INFO] [33mPress CTRL+C to quit[0m
2025-01-22 11:38:11,034 [INFO]  * Restarting with stat
2025-01-22 11:38:13,270 [WARNING]  * Debugger is active!
2025-01-22 11:38:13,279 [INFO]  * Debugger PIN: 646-228-176
2025-01-22 11:38:18,075 [INFO] Recebido JSON do Zoho: {'external_reference_id': '0000107047', 'invoice_id': '5950246000000107047', 'amount': '10.0', 'due_date': '2025-01-20', 'instructions': '', 'payer': {'name': 'Leonardo', 'tax_id': '03845768002', 'email': 'leonardogotz@gmail.com', 'address': {'street': 'José Pereira Liberato', 'number': '3350', 'complement': '', 'city': 'Itajai', 'state': 'SC', 'zip_code': '88303401'}}}
2025-01-22 11:38:18,145 [ERROR] Erro na autenticação do C6: HTTPSConnectionPool(host='api.c6bank.com.br', port=443): Max retries exceeded with url: /oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000019BDA252150>: Failed to resolve 'api.c6bank.com.br' ([Errno 11001] getaddrinfo failed)"))
2025-01-22 11:38:18,146 [ERROR] Erro na requisição ao C6: HTTPSConnectionPool(host='api.c6bank.com.br', port=443): Max retries exceeded with url: /oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000019BDA252150>: Failed to resolve 'api.c6bank.com.br' ([Errno 11001] getaddrinfo failed)"))
2025-01-22 11:38:18,147 [ERROR] Erro no processamento: HTTPSConnectionPool(host='api.c6bank.com.br', port=443): Max retries exceeded with url: /oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000019BDA252150>: Failed to resolve 'api.c6bank.com.br' ([Errno 11001] getaddrinfo failed)"))
2025-01-22 11:38:18,148 [INFO] 127.0.0.1 - - [22/Jan/2025 11:38:18] "[35m[1mPOST /zoho-webhook HTTP/1.1[0m" 500 -
